###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  29/06/1999 12:59:58
#  it declares the symbols of the Delphi unit System.pas
###

import _System

# Boolean constants
True = 1
False = 0

####################################################
class TObject:
    def Create( Self ):
        return _System.CreateObject( Self )

    def __getattr__( Self, Key ):
        return _System.Object_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _System.Object_SetAttr( Self, Key, Value )

    def __str__( Self ):
        return "<Instance of "+Self.__class__.__name__+" at "+hex(id(Self))+">"

    def __repr__( Self ):
        return str(Self)

    def __hex__( Self ):
        return hex(id(Self))

    def Free( Self ):
        if Self.__dict__.has_key("__assoc__"):
            del Self.__assoc__

# Boolean constants
True = 1
False = 0

####################################################
class TInterfacedObject( TObject ):
    def Create( Self ):
        return _System.CreateInterfacedObject( Self )

    def __getattr__( Self, Key ):
        return _System.InterfacedObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _System.InterfacedObject_SetAttr( Self, Key, Value )

