###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  06/07/1999 07:58:59
#  it declares the symbols of the Delphi unit Menus.pas
###

from System import *
from Classes import *
from Graphics import *
from ImgList import *
from ActnList import *
import _Menus

# TMenuBreak = ( mbNone, mbBreak, mbBarBreak );
mbNone = 0
mbBreak = 1
mbBarBreak = 2

# TFindItemKind = ( fkCommand, fkHandle, fkShortCut );
fkCommand = 0
fkHandle = 1
fkShortCut = 2

# TPopupAlignment = ( paLeft, paRight, paCenter );
paLeft = 0
paRight = 1
paCenter = 2

# TTrackButton = ( tbRightButton, tbLeftButton );
tbRightButton = 0
tbLeftButton = 1

####################################################
class TMenuActionLink( TActionLink ):
    def Create( Self, AClient ):
        return _Menus.CreateMenuActionLink( Self, AClient )

    def __getattr__( Self, Key ):
        return _Menus.MenuActionLink_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Menus.MenuActionLink_SetAttr( Self, Key, Value )

####################################################
class TMenuItem( TComponent ):
    def Create( Self, AOwner ):
        return _Menus.CreateMenuItem( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Menus.MenuItem_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Menus.MenuItem_SetAttr( Self, Key, Value )

####################################################
class TMenu( TComponent ):
    def Create( Self, AOwner ):
        return _Menus.CreateMenu( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Menus.Menu_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Menus.Menu_SetAttr( Self, Key, Value )

####################################################
class TMainMenu( TMenu ):
    def Create( Self, AOwner ):
        return _Menus.CreateMainMenu( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Menus.MainMenu_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Menus.MainMenu_SetAttr( Self, Key, Value )

####################################################
class TPopupMenu( TMenu ):
    def Create( Self, AOwner ):
        return _Menus.CreatePopupMenu( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Menus.PopupMenu_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Menus.PopupMenu_SetAttr( Self, Key, Value )

