###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  29/06/1999 12:59:39
#  it declares the symbols of the Delphi unit Controls.pas
###

from System import *
from Classes import *
from Graphics import *
from Menus import *
import _Controls

# TDragMessage = ( dmDragEnter, dmDragLeave, dmDragMove, dmDragDrop, dmDragCancel, dmFindTarget );
dmDragEnter = 0
dmDragLeave = 1
dmDragMove = 2
dmDragDrop = 3
dmDragCancel = 4
dmFindTarget = 5

# TAlign = ( alNone, alTop, alBottom, alLeft, alRight, alClient );
alNone = 0
alTop = 1
alBottom = 2
alLeft = 3
alRight = 4
alClient = 5

# TControlState = set of ( csLButtonDown, csClicked, csPalette, csReadingState, csAlignmentNeeded, csFocusing, csCreating, csPaintCopy );
csLButtonDown = 0
csClicked = 1
csPalette = 2
csReadingState = 3
csAlignmentNeeded = 4
csFocusing = 5
csCreating = 6
csPaintCopy = 7

# TControlStyle = set of ( csAcceptsControls, csCaptureMouse, csDesignInteractive, csClickEvents, csFramed, csSetCaption, csOpaque, csDoubleClicks, csFixedWidth, csFixedHeight, csNoDesignVisible, csReplicatable, csNoStdEvents, csDisplayDragImage, csReflector );
csAcceptsControls = 0
csCaptureMouse = 1
csDesignInteractive = 2
csClickEvents = 3
csFramed = 4
csSetCaption = 5
csOpaque = 6
csDoubleClicks = 7
csFixedWidth = 8
csFixedHeight = 9
csNoDesignVisible = 10
csReplicatable = 11
csNoStdEvents = 12
csDisplayDragImage = 13
csReflector = 14

# TMouseButton = ( mbLeft, mbRight, mbMiddle );
mbLeft = 0
mbRight = 1
mbMiddle = 2

# TDragMode = ( dmManual, dmAutomatic );
dmManual = 0
dmAutomatic = 1

# TDragState = ( dsDragEnter, dsDragLeave, dsDragMove );
dsDragEnter = 0
dsDragLeave = 1
dsDragMove = 2

# TScalingFlags = set of ( sfLeft, sfTop, sfWidth, sfHeight, sfFont );
sfLeft = 0
sfTop = 1
sfWidth = 2
sfHeight = 3
sfFont = 4

# TImeMode = ( imDisable, imClose, imOpen, imDontCare, imSAlpha, imAlpha, imHira, imSKata, imKata, imChinese, imSHanguel, imHanguel );
imDisable = 0
imClose = 1
imOpen = 2
imDontCare = 3
imSAlpha = 4
imAlpha = 5
imHira = 6
imSKata = 7
imKata = 8
imChinese = 9
imSHanguel = 10
imHanguel = 11

# TDrawingStyle = ( dsFocus, dsSelected, dsNormal, dsTransparent );
dsFocus = 0
dsSelected = 1
dsNormal = 2
dsTransparent = 3

# TImageType = ( itImage, itMask );
itImage = 0
itMask = 1

# TResType = ( rtBitmap, rtCursor, rtIcon );
rtBitmap = 0
rtCursor = 1
rtIcon = 2

# TLoadResource = ( lrDefaultColor, lrDefaultSize, lrFromFile, lrMap3DColors, lrTransparent, lrMonoChrome );
lrDefaultColor = 0
lrDefaultSize = 1
lrFromFile = 2
lrMap3DColors = 3
lrTransparent = 4
lrMonoChrome = 5

####################################################
class TDragObject( TObject ):
    def Create( Self ):
        return _Controls.CreateDragObject( Self )

    def __getattr__( Self, Key ):
        return _Controls.DragObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragObject_SetAttr( Self, Key, Value )

####################################################
class TDragControlObject( TDragObject ):
    def Create( Self, AControl ):
        return _Controls.CreateDragControlObject( Self, AControl )

    def __getattr__( Self, Key ):
        return _Controls.DragControlObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragControlObject_SetAttr( Self, Key, Value )

####################################################
class TControlCanvas( TCanvas ):
    def Create( Self ):
        return _Controls.CreateControlCanvas( Self )

    def __getattr__( Self, Key ):
        return _Controls.ControlCanvas_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ControlCanvas_SetAttr( Self, Key, Value )

####################################################
class TControl( TComponent ):
    def Create( Self, AOwner ):
        return _Controls.CreateControl( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Controls.Control_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.Control_SetAttr( Self, Key, Value )

####################################################
class TWinControl( TControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateWinControl( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedWinControl( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.WinControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.WinControl_SetAttr( Self, Key, Value )

####################################################
class TGraphicControl( TControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateGraphicControl( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Controls.GraphicControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.GraphicControl_SetAttr( Self, Key, Value )

####################################################
class TCustomControl( TWinControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateCustomControl( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedCustomControl( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.CustomControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.CustomControl_SetAttr( Self, Key, Value )

####################################################
class THintWindow( TCustomControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateHintWindow( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedHintWindow( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.HintWindow_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.HintWindow_SetAttr( Self, Key, Value )

####################################################
class TChangeLink( TObject ):
    def Create( Self ):
        return _Controls.CreateChangeLink( Self )

    def __getattr__( Self, Key ):
        return _Controls.ChangeLink_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ChangeLink_SetAttr( Self, Key, Value )

####################################################
class TCustomImageList( TComponent ):
    def Create( Self, AOwner ):
        return _Controls.CreateCustomImageList( Self, AOwner )

    def CreateSize( Self, AWidth, AHeight ):
        return _Controls.CreateSizeCustomImageList( Self, AWidth, AHeight )

    def __getattr__( Self, Key ):
        return _Controls.CustomImageList_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.CustomImageList_SetAttr( Self, Key, Value )

####################################################
class TImageList( TCustomImageList ):
    def Create( Self, AOwner ):
        return _Controls.CreateImageList( Self, AOwner )

    def CreateSize( Self, AWidth, AHeight ):
        return _Controls.CreateSizeImageList( Self, AWidth, AHeight )

    def __getattr__( Self, Key ):
        return _Controls.ImageList_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ImageList_SetAttr( Self, Key, Value )

