###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  06/07/1999 07:58:52
#  it declares the symbols of the Delphi unit Controls.pas
###

from System import *
from Classes import *
from Graphics import *
from Menus import *
from ImgList import *
from ActnList import *
import _Controls

# TDragMessage = ( dmDragEnter, dmDragLeave, dmDragMove, dmDragDrop, dmDragCancel, dmFindTarget );
dmDragEnter = 0
dmDragLeave = 1
dmDragMove = 2
dmDragDrop = 3
dmDragCancel = 4
dmFindTarget = 5

# TAlign = ( alNone, alTop, alBottom, alLeft, alRight, alClient );
alNone = 0
alTop = 1
alBottom = 2
alLeft = 3
alRight = 4
alClient = 5

# TControlState = set of ( csLButtonDown, csClicked, csPalette, csReadingState, csAlignmentNeeded, csFocusing, csCreating, csPaintCopy, csCustomPaint, csDestroyingHandle, csDocking );
csLButtonDown = 0
csClicked = 1
csPalette = 2
csReadingState = 3
csAlignmentNeeded = 4
csFocusing = 5
csCreating = 6
csPaintCopy = 7
csCustomPaint = 8
csDestroyingHandle = 9
csDocking = 10

# TControlStyle = set of ( csAcceptsControls, csCaptureMouse, csDesignInteractive, csClickEvents, csFramed, csSetCaption, csOpaque, csDoubleClicks, csFixedWidth, csFixedHeight, csNoDesignVisible, csReplicatable, csNoStdEvents, csDisplayDragImage, csReflector, csActionClient, csMenuEvents );
csAcceptsControls = 0
csCaptureMouse = 1
csDesignInteractive = 2
csClickEvents = 3
csFramed = 4
csSetCaption = 5
csOpaque = 6
csDoubleClicks = 7
csFixedWidth = 8
csFixedHeight = 9
csNoDesignVisible = 10
csReplicatable = 11
csNoStdEvents = 12
csDisplayDragImage = 13
csReflector = 14
csActionClient = 15
csMenuEvents = 16

# TMouseButton = ( mbLeft, mbRight, mbMiddle );
mbLeft = 0
mbRight = 1
mbMiddle = 2

# TDragMode = ( dmManual, dmAutomatic );
dmManual = 0
dmAutomatic = 1

# TDragState = ( dsDragEnter, dsDragLeave, dsDragMove );
dsDragEnter = 0
dsDragLeave = 1
dsDragMove = 2

# TDragKind = ( dkDrag, dkDock );
dkDrag = 0
dkDock = 1

# TScalingFlags = set of ( sfLeft, sfTop, sfWidth, sfHeight, sfFont );
sfLeft = 0
sfTop = 1
sfWidth = 2
sfHeight = 3
sfFont = 4

# TAnchorKind = ( akLeft, akTop, akRight, akBottom );
akLeft = 0
akTop = 1
akRight = 2
akBottom = 3

# TDockOrientation = ( doNoOrient, doHorizontal, doVertical );
doNoOrient = 0
doHorizontal = 1
doVertical = 2

# TImeMode = ( imDisable, imClose, imOpen, imDontCare, imSAlpha, imAlpha, imHira, imSKata, imKata, imChinese, imSHanguel, imHanguel );
imDisable = 0
imClose = 1
imOpen = 2
imDontCare = 3
imSAlpha = 4
imAlpha = 5
imHira = 6
imSKata = 7
imKata = 8
imChinese = 9
imSHanguel = 10
imHanguel = 11

# TBevelCut = ( bvNone, bvLowered, bvRaised, bvSpace );
bvNone = 0
bvLowered = 1
bvRaised = 2
bvSpace = 3

# TBevelEdge = ( beLeft, beTop, beRight, beBottom );
beLeft = 0
beTop = 1
beRight = 2
beBottom = 3

# TBevelKind = ( bkNone, bkTile, bkSoft, bkFlat );
bkNone = 0
bkTile = 1
bkSoft = 2
bkFlat = 3

####################################################
class TDragObject( TObject ):
    def Create( Self ):
        return _Controls.CreateDragObject( Self )

    def __getattr__( Self, Key ):
        return _Controls.DragObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragObject_SetAttr( Self, Key, Value )

####################################################
class TBaseDragControlObject( TDragObject ):
    def Create( Self, AControl ):
        return _Controls.CreateBaseDragControlObject( Self, AControl )

    def __getattr__( Self, Key ):
        return _Controls.BaseDragControlObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.BaseDragControlObject_SetAttr( Self, Key, Value )

####################################################
class TDragControlObject( TBaseDragControlObject ):
    def Create( Self, AControl ):
        return _Controls.CreateDragControlObject( Self, AControl )

    def __getattr__( Self, Key ):
        return _Controls.DragControlObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragControlObject_SetAttr( Self, Key, Value )

####################################################
class TDragDockObject( TBaseDragControlObject ):
    def Create( Self, AControl ):
        return _Controls.CreateDragDockObject( Self, AControl )

    def __getattr__( Self, Key ):
        return _Controls.DragDockObject_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragDockObject_SetAttr( Self, Key, Value )

####################################################
class TControlCanvas( TCanvas ):
    def Create( Self ):
        return _Controls.CreateControlCanvas( Self )

    def __getattr__( Self, Key ):
        return _Controls.ControlCanvas_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ControlCanvas_SetAttr( Self, Key, Value )

####################################################
class TControlActionLink( TActionLink ):
    def Create( Self, AClient ):
        return _Controls.CreateControlActionLink( Self, AClient )

    def __getattr__( Self, Key ):
        return _Controls.ControlActionLink_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ControlActionLink_SetAttr( Self, Key, Value )

####################################################
class TSizeConstraints( TPersistent ):
    def Create( Self, Control ):
        return _Controls.CreateSizeConstraints( Self, Control )

    def __getattr__( Self, Key ):
        return _Controls.SizeConstraints_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.SizeConstraints_SetAttr( Self, Key, Value )

####################################################
class TControl( TComponent ):
    def Create( Self, AOwner ):
        return _Controls.CreateControl( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Controls.Control_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.Control_SetAttr( Self, Key, Value )

####################################################
class TWinControlActionLink( TControlActionLink ):
    def Create( Self, AClient ):
        return _Controls.CreateWinControlActionLink( Self, AClient )

    def __getattr__( Self, Key ):
        return _Controls.WinControlActionLink_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.WinControlActionLink_SetAttr( Self, Key, Value )

####################################################
class TWinControl( TControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateWinControl( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedWinControl( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.WinControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.WinControl_SetAttr( Self, Key, Value )

####################################################
class TGraphicControl( TControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateGraphicControl( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Controls.GraphicControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.GraphicControl_SetAttr( Self, Key, Value )

####################################################
class TCustomControl( TWinControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateCustomControl( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedCustomControl( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.CustomControl_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.CustomControl_SetAttr( Self, Key, Value )

####################################################
class THintWindow( TCustomControl ):
    def Create( Self, AOwner ):
        return _Controls.CreateHintWindow( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _Controls.CreateParentedHintWindow( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _Controls.HintWindow_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.HintWindow_SetAttr( Self, Key, Value )

####################################################
class TDragImageList( TCustomImageList ):
    def Create( Self, AOwner ):
        return _Controls.CreateDragImageList( Self, AOwner )

    def CreateSize( Self, AWidth, AHeight ):
        return _Controls.CreateSizeDragImageList( Self, AWidth, AHeight )

    def __getattr__( Self, Key ):
        return _Controls.DragImageList_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DragImageList_SetAttr( Self, Key, Value )

####################################################
class TImageList( TDragImageList ):
    def Create( Self, AOwner ):
        return _Controls.CreateImageList( Self, AOwner )

    def CreateSize( Self, AWidth, AHeight ):
        return _Controls.CreateSizeImageList( Self, AWidth, AHeight )

    def __getattr__( Self, Key ):
        return _Controls.ImageList_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.ImageList_SetAttr( Self, Key, Value )

####################################################
class TDockZone(TObject):
    def Create( Self, Tree ):
        return _Controls.CreateDockZone( Self, Tree )

    def __getattr__( Self, Key ):
        return _Controls.DockZone_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DockZone_SetAttr( Self, Key, Value )

####################################################
class TDockTree( TInterfacedObject ):
    def Create( Self, DockSite ):
        return _Controls.CreateDockTree( Self, DockSite )

    def __getattr__( Self, Key ):
        return _Controls.DockTree_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.DockTree_SetAttr( Self, Key, Value )

####################################################
class TMouse(TObject):
    def Create( Self ):
        return _Controls.CreateMouse( Self )

    def __getattr__( Self, Key ):
        return _Controls.Mouse_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Controls.Mouse_SetAttr( Self, Key, Value )

