###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  06/07/1999 07:59:02
#  it declares the symbols of the Delphi unit Dialogs.pas
###

from System import *
from Classes import *
from Graphics import *
from Controls import *
from Forms import *
from StdCtrls import *
import _Dialogs

# TOpenOption = ( ofReadOnly, ofOverwritePrompt, ofHideReadOnly, ofNoChangeDir, ofShowHelp, ofNoValidate, ofAllowMultiSelect, ofExtensionDifferent, ofPathMustExist, ofFileMustExist, ofCreatePrompt, ofShareAware, ofNoReadOnlyReturn, ofNoTestFileCreate, ofNoNetworkButton, ofNoLongNames, ofOldStyleDialog, ofNoDereferenceLinks, ofEnableIncludeNotify, ofEnableSizing );
ofReadOnly = 0
ofOverwritePrompt = 1
ofHideReadOnly = 2
ofNoChangeDir = 3
ofShowHelp = 4
ofNoValidate = 5
ofAllowMultiSelect = 6
ofExtensionDifferent = 7
ofPathMustExist = 8
ofFileMustExist = 9
ofCreatePrompt = 10
ofShareAware = 11
ofNoReadOnlyReturn = 12
ofNoTestFileCreate = 13
ofNoNetworkButton = 14
ofNoLongNames = 15
ofOldStyleDialog = 16
ofNoDereferenceLinks = 17
ofEnableIncludeNotify = 18
ofEnableSizing = 19

# TFileEditStyle = ( fsEdit, fsComboBox );
fsEdit = 0
fsComboBox = 1

# TColorDialogOption = ( cdFullOpen, cdPreventFullOpen, cdShowHelp, cdSolidColor, cdAnyColor );
cdFullOpen = 0
cdPreventFullOpen = 1
cdShowHelp = 2
cdSolidColor = 3
cdAnyColor = 4

# TFontDialogOption = ( fdAnsiOnly, fdTrueTypeOnly, fdEffects, fdFixedPitchOnly, fdForceFontExist, fdNoFaceSel, fdNoOEMFonts, fdNoSimulations, fdNoSizeSel, fdNoStyleSel, fdNoVectorFonts, fdShowHelp, fdWysiwyg, fdLimitSize, fdScalableOnly, fdApplyButton );
fdAnsiOnly = 0
fdTrueTypeOnly = 1
fdEffects = 2
fdFixedPitchOnly = 3
fdForceFontExist = 4
fdNoFaceSel = 5
fdNoOEMFonts = 6
fdNoSimulations = 7
fdNoSizeSel = 8
fdNoStyleSel = 9
fdNoVectorFonts = 10
fdShowHelp = 11
fdWysiwyg = 12
fdLimitSize = 13
fdScalableOnly = 14
fdApplyButton = 15

# TFontDialogDevice = ( fdScreen, fdPrinter, fdBoth );
fdScreen = 0
fdPrinter = 1
fdBoth = 2

# TPrintRange = ( prAllPages, prSelection, prPageNums );
prAllPages = 0
prSelection = 1
prPageNums = 2

# TPrintDialogOption = ( poPrintToFile, poPageNums, poSelection, poWarning, poHelp, poDisablePrintToFile );
poPrintToFile = 0
poPageNums = 1
poSelection = 2
poWarning = 3
poHelp = 4
poDisablePrintToFile = 5

# TFindOption = ( frDown, frFindNext, frHideMatchCase, frHideWholeWord, frHideUpDown, frMatchCase, frDisableMatchCase, frDisableUpDown, frDisableWholeWord, frReplace, frReplaceAll, frWholeWord, frShowHelp );
frDown = 0
frFindNext = 1
frHideMatchCase = 2
frHideWholeWord = 3
frHideUpDown = 4
frMatchCase = 5
frDisableMatchCase = 6
frDisableUpDown = 7
frDisableWholeWord = 8
frReplace = 9
frReplaceAll = 10
frWholeWord = 11
frShowHelp = 12

# TMsgDlgType = ( mtWarning, mtError, mtInformation, mtConfirmation, mtCustom );
mtWarning = 0
mtError = 1
mtInformation = 2
mtConfirmation = 3
mtCustom = 4

# TMsgDlgBtn = ( mbYes, mbNo, mbOK, mbCancel, mbAbort, mbRetry, mbIgnore, mbAll, mbNoToAll, mbYesToAll, mbHelp );
mbYes = 0
mbNo = 1
mbOK = 2
mbCancel = 3
mbAbort = 4
mbRetry = 5
mbIgnore = 6
mbAll = 7
mbNoToAll = 8
mbYesToAll = 9
mbHelp = 10

####################################################
class TCommonDialog( TComponent ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateCommonDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.CommonDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.CommonDialog_SetAttr( Self, Key, Value )

####################################################
class TOpenDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateOpenDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.OpenDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.OpenDialog_SetAttr( Self, Key, Value )

####################################################
class TSaveDialog( TOpenDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateSaveDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.SaveDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.SaveDialog_SetAttr( Self, Key, Value )

####################################################
class TColorDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateColorDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.ColorDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.ColorDialog_SetAttr( Self, Key, Value )

####################################################
class TFontDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateFontDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.FontDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.FontDialog_SetAttr( Self, Key, Value )

####################################################
class TPrinterSetupDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreatePrinterSetupDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.PrinterSetupDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.PrinterSetupDialog_SetAttr( Self, Key, Value )

####################################################
class TPrintDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreatePrintDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.PrintDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.PrintDialog_SetAttr( Self, Key, Value )

####################################################
class TFindDialog( TCommonDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateFindDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.FindDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.FindDialog_SetAttr( Self, Key, Value )

####################################################
class TReplaceDialog( TFindDialog ):
    def Create( Self, AOwner ):
        return _Dialogs.CreateReplaceDialog( Self, AOwner )

    def __getattr__( Self, Key ):
        return _Dialogs.ReplaceDialog_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _Dialogs.ReplaceDialog_SetAttr( Self, Key, Value )

