###
#  This file was generated by VCL Generator
#  Copyright 1998 - Morgan Martinet
#  06/07/1999 07:59:00
#  it declares the symbols of the Delphi unit ExtCtrls.pas
###

from System import *
from Classes import *
from Controls import *
from Forms import *
from Menus import *
from Graphics import *
from StdCtrls import *
import _ExtCtrls

# TShapeType = ( stRectangle, stSquare, stRoundRect, stRoundSquare, stEllipse, stCircle );
stRectangle = 0
stSquare = 1
stRoundRect = 2
stRoundSquare = 3
stEllipse = 4
stCircle = 5

# TBevelStyle = ( bsLowered, bsRaised );
bsLowered = 0
bsRaised = 1

# TBevelShape = ( bsBox, bsFrame, bsTopLine, bsBottomLine, bsLeftLine, bsRightLine, bsSpacer );
bsBox = 0
bsFrame = 1
bsTopLine = 2
bsBottomLine = 3
bsLeftLine = 4
bsRightLine = 5
bsSpacer = 6

# TResizeStyle = ( rsNone, rsLine, rsUpdate, rsPattern );
rsNone = 0
rsLine = 1
rsUpdate = 2
rsPattern = 3

# TBandPaintOption = ( bpoGrabber, bpoFrame );
bpoGrabber = 0
bpoFrame = 1

####################################################
class TShape( TGraphicControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateShape( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Shape_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Shape_SetAttr( Self, Key, Value )

####################################################
class TPaintBox( TGraphicControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreatePaintBox( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.PaintBox_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.PaintBox_SetAttr( Self, Key, Value )

####################################################
class TImage( TGraphicControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateImage( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Image_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Image_SetAttr( Self, Key, Value )

####################################################
class TBevel( TGraphicControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateBevel( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Bevel_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Bevel_SetAttr( Self, Key, Value )

####################################################
class TTimer( TComponent ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateTimer( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Timer_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Timer_SetAttr( Self, Key, Value )

####################################################
class TCustomPanel( TCustomControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateCustomPanel( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedCustomPanel( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.CustomPanel_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.CustomPanel_SetAttr( Self, Key, Value )

####################################################
class TPanel( TCustomPanel ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreatePanel( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedPanel( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Panel_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Panel_SetAttr( Self, Key, Value )

####################################################
class TPage( TCustomControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreatePage( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedPage( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Page_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Page_SetAttr( Self, Key, Value )

####################################################
class TNotebook( TCustomControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateNotebook( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedNotebook( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Notebook_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Notebook_SetAttr( Self, Key, Value )

####################################################
class THeader( TCustomControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateHeader( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedHeader( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Header_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Header_SetAttr( Self, Key, Value )

####################################################
class TCustomRadioGroup( TCustomGroupBox ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateCustomRadioGroup( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedCustomRadioGroup( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.CustomRadioGroup_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.CustomRadioGroup_SetAttr( Self, Key, Value )

####################################################
class TRadioGroup( TCustomRadioGroup ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateRadioGroup( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedRadioGroup( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.RadioGroup_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.RadioGroup_SetAttr( Self, Key, Value )

####################################################
class TSplitter( TGraphicControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateSplitter( Self, AOwner )

    def __getattr__( Self, Key ):
        return _ExtCtrls.Splitter_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.Splitter_SetAttr( Self, Key, Value )

####################################################
class TCustomControlBar( TCustomControl ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateCustomControlBar( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedCustomControlBar( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.CustomControlBar_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.CustomControlBar_SetAttr( Self, Key, Value )

####################################################
class TControlBar( TCustomControlBar ):
    def Create( Self, AOwner ):
        return _ExtCtrls.CreateControlBar( Self, AOwner )

    def CreateParented( Self, ParentWindow ):
        return _ExtCtrls.CreateParentedControlBar( Self, ParentWindow )

    def __getattr__( Self, Key ):
        return _ExtCtrls.ControlBar_GetAttr( Self, Key )

    def __setattr__( Self, Key, Value ):
        return _ExtCtrls.ControlBar_SetAttr( Self, Key, Value )

